### ISSUE TITLE
Inclusion of more synonyms

### ISSUE THREAD

**Issue by WinslowJosiah** [Mercerenies/acrostic-lang#1]
Upon seeing the docs for this esolang, I was surprised to see that a few choices of synonym were absent from the language. Here are my suggestions for more synonyms.

|   Word   |              Synonym Proposals             |
|:--------:|:------------------------------------------:|
|   START  | COMMENCE, COMMENCED, COMMENCES, COMMENCING |
|   ZERO   |                     ZIP                    |
|    ONE   |                    SOLO                    |
|    TWO   |                 DUET, DUETS                |
|   GROSS  |                   GROSSES                  |
|   ASCII  |          SYMBOL, SYMBOLIC, SYMBOLS         |
|    ADD   |               PLUS, SUMMATION              |
| SUBTRACT |                    MINUS                   |
| RETRIEVE |            RETRIEVAL, RETRIEVALS           |
|  BRANCH  |   CONTINGENCIES, CONTINGENCY, CONTINGENT   |

Adding these synonyms to the language would be much appreciated!

**Comment by Mercerenies** [comment]
Oh, hey! Someone else actually cares about this. Neat! More synonyms are always welcome, so thanks a ton and happy coding! :)

**Comment by WinslowJosiah** [comment]
You're welcome, this is an excellent esolang idea!

I'm also working on a Python interpreter that I'm excited to finish up and show you.

**Comment by WinslowJosiah** [comment]
Ooh, forgot to suggest DUOS as a synonym for TWO.
